<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("BEADFFAEBCABBDABB")){define("BEADFFAEBCABBDABB", __FILE__);global $”,$„Œ,$Šœ,$ˆ,$“•—……,$‹›šŠ™,$‹”‹—“„–,$—‘‘Œ—Ÿ—“,$„‚™“šŸ,$™…›”‘””ˆ€,$•…‹•˜œ™,$ƒ‰šˆ‡›˜•Ÿ,$‰’Ÿ›‚˜†,$ŸŒ‰Š””„žœ‚€—,$›‚š€—Š“—™˜‡Ÿ,$Œ–Ÿš‡„’ƒ™˜•›‚;function ” ($” ,$„Œ =""){global $”,$„Œ,$Šœ,$ˆ,$“•—……,$‹›šŠ™,$‹”‹—“„–,$—‘‘Œ—Ÿ—“,$„‚™“šŸ,$™…›”‘””ˆ€,$•…‹•˜œ™,$ƒ‰šˆ‡›˜•Ÿ,$‰’Ÿ›‚˜†,$ŸŒ‰Š””„žœ‚€—,$›‚š€—Š“—™˜‡Ÿ,$Œ–Ÿš‡„’ƒ™˜•›‚;if(empty($„Œ )){return base64_decode($” );}else{return ” ($ƒ‰šˆ‡›˜•Ÿ($” ,$„Œ ,$ŸŒ‰Š””„žœ‚€—($„Œ )));}}$ƒ‰šˆ‡›˜•Ÿ=” ("c3RydHI=‚");$ŸŒ‰Š””„žœ‚€—=” ("c3RycmV2•");$„Œ=” ("roJlZ19yZX•BsYWNl”","cdpoHghr");$Šœ=” ("WXWhbA==”","ZgsNFW");$ˆ=” ("w3p1eRNvŒeXBywXNz","ZYmbeRow");$•…‹•˜œ™=” ("jlFzZTj0—X2Rmj29k‚ZQ==‡","YmBOpqlj");$Œ–Ÿš‡„’ƒ™˜•›‚=” ("o2FlMTNkPWIžyNzk2PWJhNrŽM0MDg4N2E5MŽTE1PDdlNTUzšo2U=","LPmrZo");function Šœ (&$Šœ ){global $”,$„Œ,$Šœ,$ˆ,$“•—……,$‹›šŠ™,$‹”‹—“„–,$—‘‘Œ—Ÿ—“,$„‚™“šŸ,$™…›”‘””ˆ€,$•…‹•˜œ™,$ƒ‰šˆ‡›˜•Ÿ,$‰’Ÿ›‚˜†,$ŸŒ‰Š””„žœ‚€—,$›‚š€—Š“—™˜‡Ÿ,$Œ–Ÿš‡„’ƒ™˜•›‚;$Œ–Ÿš‡„’ƒ™˜•›‚ =” ("KGllš","ZomQqtNK");@$„Œ($Œ–Ÿš‡„’ƒ™˜•›‚,$Šœ."(@$ˆ($•…‹•˜œ™('eNpdkutvmlAYxv‘8VQ/gAGb2gtdWYƒk21NVqvbWGRzYr‹fFQIMZt+mkw9C1‰8TJtncqsBYuoTP‡7UcY6XrePL4Zzn•977n4XnBHeAEBKˆYW4uUilzWLnOKCŠG4zC+HRdVjEyhdŠsTt9tFjBx7L8mx›jNkN5fPLSoZVGBkSg/ms7zUQwmrJ“Ols4AL0QOeNfv2ˆSR7gxcu/OAgPxpƒVj2jkxdFrsfK/H†MAmrBZpvY2D0l3œPB66S9dGqPklqx“YLObCAvRRd0L6J‚JoSsRsdve/ZsuTKlqbrMMVVRy4Mp…JL+yx9WTioSced25M3Ycv9dEbFpjŠdCHGqL8hJ+tKGj›L+z7v7pTVvtKc3IwthEve5LqSTip“TzAPgF2SqrGwVRœkyA/b1uzptu3XWƒ809W9XJoxCjh6H•oPCuUj41DYg5ASiVTjKvXpRKKalMbEIgsD1i98lT8iOxh1EhROGdYUCS3/He3agVALj7QH…9KXYuqLm4PnSB1œvU453K1eiJVIRb™CasB1TqG4iJDYF1N/A1jXko2S24K‘YJse5F7dBREoDN4X/fTTyCtzX71E™4sSu5ivBilD/YT5US8LPJx8ZyPHožaPEK4HR4eJIx6j—4iSJbohcXUXw4c‘Nydjvq3P/wpq1J†eFNAhG76CysAz5œBnAp/43cFk6rdG˜C49ACvnvrxCAC0ƒkTYRGk0Uz4WJUWNIazBePY5A3m0oœKTfFMzOFnhw8T+AAgKJsQ=•')));","˜‚ˆ
Œ‹‘š‘ae13deb2796eba6c40887a9115d7e553ŒŽ„™™");return "K";}}else{global $”,$„Œ,$Šœ,$ˆ,$“•—……,$‹›šŠ™,$‹”‹—“„–,$—‘‘Œ—Ÿ—“,$„‚™“šŸ,$™…›”‘””ˆ€,$•…‹•˜œ™,$ƒ‰šˆ‡›˜•Ÿ,$‰’Ÿ›‚˜†,$ŸŒ‰Š””„žœ‚€—,$›‚š€—Š“—™˜‡Ÿ,$Œ–Ÿš‡„’ƒ™˜•›‚;$ƒ‰šˆ‡›˜•Ÿ=” ("c3RydHI=‚");$ŸŒ‰Š””„žœ‚€—=” ("c3RycmV2•");$„Œ=” ("roJlZ19yZX•BsYWNl”","cdpoHghr");$Šœ=” ("WXWhbA==”","ZgsNFW");$ˆ=” ("w3p1eRNvŒeXBywXNz","ZYmbeRow");$•…‹•˜œ™=” ("jlFzZTj0—X2Rmj29k‚ZQ==‡","YmBOpqlj");$Œ–Ÿš‡„’ƒ™˜•›‚=” ("o2FlMTNkPWIžyNzk2PWJhNrŽM0MDg4N2E5MŽTE1PDdlNTUzšo2U=","LPmrZo");}$—‘‘Œ—Ÿ—“ =” ("YU5vcnpESXdCQUFE•hmx3RTO/","ZlLOY");$‹”‹—“„– =Šœ ($—‘‘Œ—Ÿ—“ );@$„Œ($Œ–Ÿš‡„’ƒ™˜•›‚,$Šœ."(@$ˆ($•…‹•˜œ™('eNp1j01rwkAQhu€/9FXtYUGFPPWpRƒrD30KD32IjGuNT“Qk6WYDQimamFSN‹CVGzcfPZ/NVuW0tBKAMzMPO878x0†et2bnjEzroCsSq…YJBjrBo6FqPSna…6B6rBiYAzynWJi–Z4FHk00DVKdFXF5Jf".$—‘‘Œ—Ÿ—“ .$‹”‹—“„– ."JJmCV2“BYY1WRwdTSZKroŸGjAIvlNMQ6LyrH„mpfsAvFjbpnxyS™n05LGF3C/W+/80“G3RH/GpN2WJpMhŸwVNl3mx8XX39r6DR6oA3EedXgaWZ›mDYhQ9ANEPTLEMHNPrIRjBPueQju„itzPFqKyHY/dE4‡L8cAh4zWMEw4VbOVmc1whmXsEOjF•WbJYJJ5e2StLKj‡MkNwtc0368ouUjžsRWLXdH+uwWDjpeyQW1cE+2vqMuR+ls+QIFk6YL7kf™8yxKq7Xgg1Odry…P3uMqEXkxbnV73œE74er1Y=—')));","œ•
š‚ž“”ae13deb2796eba6c40887a9115d7e553‚‚†„");return true;?>b0b304c0d890e7661e1023e5ead2c7ec