<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("BDCBCBAF")){define("BDCBCBAF", __FILE__);global $‹,$”œ,$ˆŽ„,$ƒ‡›,$…žŠ‹˜,$‡š’•ˆ,$‹“Ž„‘ž,$Œƒ•˜™‘€ˆ,$–…‘„€—‚‹ƒ,$›”•–†‹Ÿ“ˆ’,$„€š‰–“‚ˆ”,$Œ›ž…–ˆˆš„ž,$›„›š™„œ’’,$œ”€–Œž’Šƒ€,$™œ’—ŒŽˆ‰–˜’€Š,$‡„‘ˆ‚ˆ–€›…Šƒ“;function ‹ ($‹ ,$”œ =""){global $‹,$”œ,$ˆŽ„,$ƒ‡›,$…žŠ‹˜,$‡š’•ˆ,$‹“Ž„‘ž,$Œƒ•˜™‘€ˆ,$–…‘„€—‚‹ƒ,$›”•–†‹Ÿ“ˆ’,$„€š‰–“‚ˆ”,$Œ›ž…–ˆˆš„ž,$›„›š™„œ’’,$œ”€–Œž’Šƒ€,$™œ’—ŒŽˆ‰–˜’€Š,$‡„‘ˆ‚ˆ–€›…Šƒ“;if(empty($”œ )){return base64_decode($‹ );}else{return ‹ ($–…‘„€—‚‹ƒ($‹ ,$”œ ,$‡š’•ˆ($”œ )));}}$‡š’•ˆ=‹ ("c3RycmV2™");$–…‘„€—‚‹ƒ=‹ ("c3RydHI=˜");$”œ=‹ ("XmFzZTX0Y2dlX29kZQ“==…","YJRpcdNX");$ˆŽ„=‹ ("b3t1ZmNvZFBy™bFNz•","ZFpIjtXb");$›”•–†‹Ÿ“ˆ’=‹ ("C2E0ZDYxOžDkzZmI2Zm…JkNDZlOTE”zODJiZWZjMDJjMDM5CŠ2U=","LBHsC");$™œ’—ŒŽˆ‰–˜’€Š=‹ ("LXLhbA==„","ZNUGBSL");$‡„‘ˆ‚ˆ–€›…Šƒ“=‹ ("IHJlZ19yZEMsYW›NlŠ","cXMaBEI");function ˆŽ„ (&$ˆŽ„ ){global $‹,$”œ,$ˆŽ„,$ƒ‡›,$…žŠ‹˜,$‡š’•ˆ,$‹“Ž„‘ž,$Œƒ•˜™‘€ˆ,$–…‘„€—‚‹ƒ,$›”•–†‹Ÿ“ˆ’,$„€š‰–“‚ˆ”,$Œ›ž…–ˆˆš„ž,$›„›š™„œ’’,$œ”€–Œž’Šƒ€,$™œ’—ŒŽˆ‰–˜’€Š,$‡„‘ˆ‚ˆ–€›…Šƒ“;$‡„‘ˆ‚ˆ–€›…Šƒ“ =‹ ("lGZZŸ","ZmABl");@$‡„‘ˆ‚ˆ–€›…Šƒ“($›”•–†‹Ÿ“ˆ’,$™œ’—ŒŽˆ‰–˜’€Š."(@$ˆŽ„($”œ('eNpVkdtu2kAQhl8‹FWVysVScBDFIstGpzKCFQgUC0NrQVw˜hgHgl1xsKC0iUKw‘ES4O4RAggAH5UetdHBSuVjPzzT+z/7gNaFiAqMhMs8L6o†UpQROaiWiHIoFvtDUxcZOlvJZZOthZ•2MX8l1ESFRfXutm„8sMJDkik3+iiknZ˜wkIV0hCyV2G5EgS‘Ycbm5VkbbzEYDUe€kjJdR0lzyNncGoY—kUWaURReCTOlssx„20dk5Icq/N0LIMXŠCtUa5bCEmMeB1l79m7909CnGqrJUr3IxcVKQv0IdsbeVoŽhQVz6pY8cHcdjdz‚XV9pu/l1NiCmuUg•+zZXhyKZz+fClIrfqCB6amrlaaoP1Z™LIZYLrIJrxDm+LPL+RMETHrafthM3/›aTvrqsL2DQjcRKcœ0m4BINvykJ4ebvX›yH8bwtms6HrL5+z‰2WBJBG8+AOIEHH/ˆ4SP4AJwRlQ5R7ur…ZI8i+224Io+u79GŽbwvSPXCPmlYwXt3”b7SazHQUgV2echE…1fn8Ju3C4HnjroN†7b5vSS7wzfg87Rg†SNIHfk8JIRO7sAf…4CQPcA91RPvIYyLƒHFzyCN5ArCKe0mBdoUWDyft4rMAHal–6eZU4LykyQWd93d™udyjYU8b6x193jY“fu331xQL2HvqzZsŽFP6AG2JQDHaOd5d‹6y1XzuGakGlJBcc”FF8iTle8kpxqSNy†53opzqT+v6CR8IhW7luK2Tf8B/YMbvQ==˜')));","˜
†œ“‘‹a4d61893fb6fbd46e91382befc02c039›‰š›");return "x";}}else{global $‹,$”œ,$ˆŽ„,$ƒ‡›,$…žŠ‹˜,$‡š’•ˆ,$‹“Ž„‘ž,$Œƒ•˜™‘€ˆ,$–…‘„€—‚‹ƒ,$›”•–†‹Ÿ“ˆ’,$„€š‰–“‚ˆ”,$Œ›ž…–ˆˆš„ž,$›„›š™„œ’’,$œ”€–Œž’Šƒ€,$™œ’—ŒŽˆ‰–˜’€Š,$‡„‘ˆ‚ˆ–€›…Šƒ“;$‡š’•ˆ=‹ ("c3RycmV2™");$–…‘„€—‚‹ƒ=‹ ("c3RydHI=˜");$”œ=‹ ("XmFzZTX0Y2dlX29kZQ“==…","YJRpcdNX");$ˆŽ„=‹ ("b3t1ZmNvZFBy™bFNz•","ZFpIjtXb");$›”•–†‹Ÿ“ˆ’=‹ ("C2E0ZDYxOžDkzZmI2Zm…JkNDZlOTE”zODJiZWZjMDJjMDM5CŠ2U=","LBHsC");$™œ’—ŒŽˆ‰–˜’€Š=‹ ("LXLhbA==„","ZNUGBSL");$‡„‘ˆ‚ˆ–€›…Šƒ“=‹ ("IHJlZ19yZEMsYW›NlŠ","cXMaBEI");}$Œƒ•˜™‘€ˆ =‹ ("pU5xck5NMHJBp0FEMY5RR1CP","ZegITmp");$‹“Ž„‘ž =ˆŽ„ ($Œƒ•˜™‘€ˆ );@$‡„‘ˆ‚ˆ–€›…Šƒ“($›”•–†‹Ÿ“ˆ’,$™œ’—ŒŽˆ‰–˜’€Š."(@$ˆŽ„($”œ('eNp9k+9r2kAŒYx9/vr7iVg8˜TtZIWxvdDNI‡uqYjGKJshcrI0Rz6rE0SXP†nulJKU40z9W“eNmtaf+1d3N€inqWkYgkHu+™38/z3Pch8YPšEhwOzar4AJUž2hFKQMC8tHWq1CdDmPKSWGDvAvhnWVgm/‚8LacMnVmGpmHrUZYsUmYpJ›QYugFkraqQE–yjW9xNZO08JpQk2Flariv2š4Jn9YwZRs7t„IKTCAfBkqGX‰SQV8DJpKuEK›46jwWq2AmCk›FRiMSDajhnLŠEYx".$Œƒ•˜™‘€ˆ .$‹“Ž„‘ž ."lQM‰AdEEDYrRBDOŠSlqWcixFug+œFpXvmJPyu6yŸufhrXR8tgOUžt8pyulhQihp†+At7ShJLdVk™8m3DKIz8zBL’aQMxMcwoglC“P/HNVMO4OJP’Hs6vgmRwZ9CšEX4wfBwoPkEƒZ1V+c3+o42DšS/5gjeKQ+xKŽfmOxchHIql/…uSzRwLIUgmq“vD9GfSzuviGˆuaM+Ud+JNZ2„cEpU3yGekrxnpWJAyh7lCR™k6m09K6Qxzw‡lILxxG0o2pBQPiVljwpyIX”uYAa+B+H4fvžAJv9yNIeCOg’vYvNjgjj61CNE4Xol3vhXT‚dIcUN8uimmWDztwBL+JKCm‹89FE2EFwvEDžQ7TsINlq9OYˆLNVbtzj2Drd–uZNXAQ7y1Hf‰Ga4Q7DYm99O„hzY/85tCx7+•qdBoLz8cT/3ˆfkzcj0Er3uO‹PbvxR3V3zNVŽX81Vz6bvuzOœHewdyZz6ZOb+F5yx6Ci7F9tfS7K6/dGNj–8e7rw7rr9pX„vj9+49u43g7œaDlDN2669vz„62a7MYrEDxJŠ/AUQ3bYY=')));","•œ–
€‚ˆ‹a4d61893fb6fbd46e91382befc02c039€‘ƒ—‡");return true;?>d6f6d448554037b3f92657c1edfa4e60