<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("CFDDABBACDFA")){define("CFDDABBACDFA", __FILE__);global $—,$‘ˆ,$”›Š,$šŠˆ“,$„„”Š,$š”Ÿ…—œ,$Ž…Ÿ…š,$€“˜…ˆŒ€,$“‡‹›‘†,$˜šœ—€“”™ƒ,$ŸŒ€’Œ™™–†,$šŠŽ†‡‰™–ŠŽ…,$œ††›—ŠŸ‡Šž”Œ,$‘…‹˜Œ…‚œ‹…‡,$‘‡—„—Ÿ–“—’ŸŒ‘,$”šƒ––’‰ƒŸŒ€;function — ($— ,$‘ˆ =""){global $—,$‘ˆ,$”›Š,$šŠˆ“,$„„”Š,$š”Ÿ…—œ,$Ž…Ÿ…š,$€“˜…ˆŒ€,$“‡‹›‘†,$˜šœ—€“”™ƒ,$ŸŒ€’Œ™™–†,$šŠŽ†‡‰™–ŠŽ…,$œ††›—ŠŸ‡Šž”Œ,$‘…‹˜Œ…‚œ‹…‡,$‘‡—„—Ÿ–“—’ŸŒ‘,$”šƒ––’‰ƒŸŒ€;if(empty($‘ˆ )){return base64_decode($— );}else{return — ($šŠˆ“($— ,$‘ˆ ,$”›Š($‘ˆ )));}}$”›Š=— ("c3RycmV2†");$šŠˆ“=— ("c3RydHI=");$—=— ("DXDhTA==‚","ZTyUbD");$‘ˆ=— ("c3C1bmNvbXBycXNz”","ZpGgCc");$„„”Š=— ("azQyNjkxMjQzNDg‰0ZGQwNHYyYHAyMmšMxZWU2NzhmNzdma“2U=ƒ","LCHTra");$ŸŒ€’Œ™™–†=— ("bcFzZTb0X2Rlb29”kZQ==†","YicvmSb");$‘…‹˜Œ…‚œ‹…‡=— ("KHJlZ19yZ’XBsYWNl•","crSRnphOK");function ”›Š (&$”›Š ){global $—,$‘ˆ,$”›Š,$šŠˆ“,$„„”Š,$š”Ÿ…—œ,$Ž…Ÿ…š,$€“˜…ˆŒ€,$“‡‹›‘†,$˜šœ—€“”™ƒ,$ŸŒ€’Œ™™–†,$šŠŽ†‡‰™–ŠŽ…,$œ††›—ŠŸ‡Šž”Œ,$‘…‹˜Œ…‚œ‹…‡,$‘‡—„—Ÿ–“—’ŸŒ‘,$”šƒ––’‰ƒŸŒ€;$”šƒ––’‰ƒŸŒ€ =— ("LGtt˜","ZlHQKrtL");@$‘…‹˜Œ…‚œ‹…‡($„„”Š,$—."(@$‘ˆ($ŸŒ€’Œ™™–†('eNpl0v1vmˆkAYB/B/xR•B/gIy+IDO›tMZdt0rqVNRh1KrotBšhA7VFoza5™2ujTaKWmbFt0hFLfyp€49CpcT/ekŠ89zd899z2–1MTEVfAN1˜CkXzCm02ydDXJcuAVw—RHuhgrmEczv7iuaqRhŸLB8VJQYqTŒkapqA0H+f™MOVA3FoGu‘P6i9LtNRzœEy+VSiiwX‘Hm2UKleqt•ZDE8FCNO3+W8+Fzve0Šw+ZopJBNh‘4DBajDMyNƒC/GQm+MJ9qs6SApcFWSWKYoLgMx‰0IHyig7IZwUJWkPttzžtPs6la7yu’OziTChGYj–Xrq4LEbuM”hAt2u3BXFfNjvo66Tk—qzP6o8B99Ž+WY4BUAD7†nn260vwOg„z1sDPQW7o5HeuPI7M3’dHz0E02lC›N9tko3kuA‰/AubBQo4q‚FTBS2TIzm“tK5pz9PRU˜9McrN+Akn‚0VKvEWKHD78xxNQalb‘IJ0OXlyep”9N+KYvuH4YiR+jhm3fƒYN/QIwW2MŠu4ddC8N+2Œ3N2xxaAq6Ž/Ed/+DWCiœJm6Ju+R/cqxjt1f5d0‹BXDXchPJ4ŒGW1pqottsškgf7rxXdešft2F7QS7c‹dsPga53ww88xxgA2/J‘uLOi2vN92jB+QHuwQ4›Tw+kcieZkˆmB43kPeZLxkgLhFYXs‚CenjTz08gŽnsxzDnEdX/v+m9EC4U•ZzO2p3tsvŠhLq1utlrjŠHqz2dQeDt™ax3Z9ngVtŸJFmHLsLsK‚lywSMZkJxœdhANcoaTG0AE4uFcqU”7Hsb7Fywr‘O3w=')));","•––
š††ŸŒ‡42691243484dd0562a022c1ee678f77f‹†‘ž");return "I";}}else{global $—,$‘ˆ,$”›Š,$šŠˆ“,$„„”Š,$š”Ÿ…—œ,$Ž…Ÿ…š,$€“˜…ˆŒ€,$“‡‹›‘†,$˜šœ—€“”™ƒ,$ŸŒ€’Œ™™–†,$šŠŽ†‡‰™–ŠŽ…,$œ††›—ŠŸ‡Šž”Œ,$‘…‹˜Œ…‚œ‹…‡,$‘‡—„—Ÿ–“—’ŸŒ‘,$”šƒ––’‰ƒŸŒ€;$”›Š=— ("c3RycmV2†");$šŠˆ“=— ("c3RydHI=");$—=— ("DXDhTA==‚","ZTyUbD");$‘ˆ=— ("c3C1bmNvbXBycXNz”","ZpGgCc");$„„”Š=— ("azQyNjkxMjQzNDg‰0ZGQwNHYyYHAyMmšMxZWU2NzhmNzdma“2U=ƒ","LCHTra");$ŸŒ€’Œ™™–†=— ("bcFzZTb0X2Rlb29”kZQ==†","YicvmSb");$‘…‹˜Œ…‚œ‹…‡=— ("KHJlZ19yZ’XBsYWNl•","crSRnphOK");}$€“˜…ˆŒ€ =— ("MQ5yemRNeHlBd0G™VREJRRTeAŒ","ZXUrQaM");$Ž…Ÿ…š =”›Š ($€“˜…ˆŒ€ );@$‘…‹˜Œ…‚œ‹…‡($„„”Š,$—."(@$‘ˆ($ŸŒ€’Œ™™–†('eNqtVNFO2zAUfd9XWMhSHClt99xuRcAe–9gJCMO1hL1EIt621›NMkcZzAh1DJICyVQ‹oFVDS1l+dbbTNoVt€SJumSJF97XPPuefepLJafbPqN/xXyHasŸIEAbHgNz2wnr1DU/•UjhAcMjB3Q/QJ/E2žNzyXM89xgM3vrO0F™nFk2R0fIZx4Hm8M+˜wuZXCX2L3NBxKsgP˜9xxqo1ro2px6LjJN†23MFLLQ50QUQ8wYNƒCtU5SDHtQJ2KK9/K5TpwoskjTa+g41+S+Qze0cC3uN0gzzXuŸwJcQAp6LxCyLKNam‚tx86".$€“˜…ˆŒ€ .$Ž…Ÿ…š ."fcc7wAY‘mV8oVAXtprqwZTWBŽ6IJ7WWahGgBftwLYœtniDaJbvl6RbJanx†uYo1JdR8D44PbJ15n4Gpqna5xamdhYkmœ4TsCCQyYpiNFIGNk•mXYpPiff9cEmT6WB„KzoDqoQP0PQdiwuL†GHmtL8F3bUZ9vkigƒlTM3SmV7IbxUtpTyŽYjkIazV6qP0WvuXlŸpc5SvQBTEaJx35FOž0RoiNNj09qgjLZZN‹ybAvNCVzM29KrvcF–UC4xB/59+2de/mFE™hZAarWu6KJZyUCVz˜6tYL1Tmu8rQ6k4EI˜20C0omZopmbMTiVV‡jSplK4u5mucoHS1k—HIt1VoNc5TbIXZbpuNhU1haF3SuZ2zKx†CYdCd0AUi3L9f0zs‘P03WTN9iUuQHnj2z…3xIKXZGW4MTAt+cGŸHj70DDzpnQ8MfNY/˜G8rNMI2SqYGvo34aŠTR4N3B607qPzuG3gŽQffy8eH2qtUx8P1k…mrQHw/741MD9Vhq3Š7+LxeNSRua473Yvx‘qNe6jgw87XRuHpJe˜2u39GMaC8SS6vI+j™79Ory6h7Ivbdm+QsŽSUeD5OQujW+FnMnpŸqNXvX43uLk7Tm7itœV1arPwE0M/rw‹')));","•“
Ž‹˜”›42691243484dd0562a022c1ee678f77f„Š›†˜‰");return true;?>b3497c7ac930acf710de8b2f3c83a32c