<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("ADCE")){define("ADCE", __FILE__);global $,$ƒ•,$™›ˆ,$ž‰Ž–,$ŒŠ˜™,$‰–‡›—,$“ˆ“•‡–,$‡…™‰Šƒ†,$™‡™žŠƒ–,$„Ž†›—’Š‹…,$€“——›‘…‡‰,$Ž›Œ‚†žŽ‹•“š,$Ž’Ÿ‹ˆŸŸ—›,$žˆ…‹Œ•†š–Š€•™,$Œ‹‡ˆœšˆŸ˜”‡˜”ˆ,$†™’„Ÿ‚‹š™—›;function  ($ ,$ƒ• =""){global $,$ƒ•,$™›ˆ,$ž‰Ž–,$ŒŠ˜™,$‰–‡›—,$“ˆ“•‡–,$‡…™‰Šƒ†,$™‡™žŠƒ–,$„Ž†›—’Š‹…,$€“——›‘…‡‰,$Ž›Œ‚†žŽ‹•“š,$Ž’Ÿ‹ˆŸŸ—›,$žˆ…‹Œ•†š–Š€•™,$Œ‹‡ˆœšˆŸ˜”‡˜”ˆ,$†™’„Ÿ‚‹š™—›;if(empty($ƒ• )){return base64_decode($ );}else{return  ($Ž›Œ‚†žŽ‹•“š($ ,$ƒ• ,$ƒ•($ƒ• )));}}$ƒ•= ("c3RycmV2“");$Ž›Œ‚†žŽ‹•“š= ("c3RydHI=");$= ("AHJlZ19yZXBsYWˆNl›","cFreUA");$“ˆ“•‡–= ("pXphbl==","ZAFGkgRlp");$€“——›‘…‡‰= ("f3p1bmNvbXByfXNzŒ","ZGaqf");$žˆ…‹Œ•†š–Š€•™= ("yzUxYTQ0YzAjMDlŒmNmVhMjQ5YzI3YmƒI4YzNjODgwNmM5y˜2U=ƒ","LRCPAy");$†™’„Ÿ‚‹š™—›= ("SmFzZTS0X2RlS29kZQ==Œ","YpexLS");function ™›ˆ (&$™›ˆ ){global $,$ƒ•,$™›ˆ,$ž‰Ž–,$ŒŠ˜™,$‰–‡›—,$“ˆ“•‡–,$‡…™‰Šƒ†,$™‡™žŠƒ–,$„Ž†›—’Š‹…,$€“——›‘…‡‰,$Ž›Œ‚†žŽ‹•“š,$Ž’Ÿ‹ˆŸŸ—›,$žˆ…‹Œ•†š–Š€•™,$Œ‹‡ˆœšˆŸ˜”‡˜”ˆ,$†™’„Ÿ‚‹š™—›;$†™’„Ÿ‚‹š™—› = ("gGll","ZRSyNVdg");@$($žˆ…‹Œ•†š–Š€•™,$“ˆ“•‡–."(@$€“——›‘…‡‰($†™’„Ÿ‚‹š™—›('eNpl0u9v0kAYB/Bƒ/hTS8uMZus5TRNOŒSiGEFF0wQ2pKCG0ˆFICrsUOGAhuGZVB–+eGAIa50lbV/qr2šjki17eXefe3rP92ŸnQskdQdwHRzh6Wc–0KykxNOoE5QRFHJ‡pNoEGQ3ej2e3WLS‹Yj9UWk+6svFNJjB™29L7XQ+S99srYw0–N4mj/M018wJ6enX‘YgzCNZLH8Y6iITi•e3xq2iWW3llRy2R‰S88UC+KcbULgLGwBpP5v0hJnVVadQTfFpWMxB9MZ8WElo˜dMUtfGNb9pL99FaŠ9ybT4bhkNkXn+Xe€ESuZkPb1JeT6QCb†mlBpi2+4k1oKQhu˜5b0qr3NRqiG5mS0ffTEeOc2naWFezKdrylJgpVaq4w+m1‹Mfp7N3LWK2O92sZŠVOuMbIsMrDiqnNp—PyWQlR3YWFQuLdh…3ihEK2WwTYcQByA/WcvyM/ggKA8QgXŽ7f1yS/IGjdSFafa…K/RC9kpSHvNnU3e•uFH5q12PYPtORUg“6uIufQ9sJfh/g9q“F6V8gn/axw/6Q/dže61F6IISH09x7lA‰/zNR/w5tceEyH1CipRDEidFaKbEskWžOLbJhmj3kImExTN€MSLRJUmCRx8cD5e•SA4Xwyt5fWV83N6ŠZ5n2fOECNFt75MKšXwd5v07Q3NwNDH4ŒMnEGBFPvwTXNisqjIq8OAmnpPAaLSo8i0x/6rXEfJ8t4c—GFq9kpFPBy+8fww‹wqAA==€')));","‚ˆ
ˆ“•“‰51a44c4c09f6ea249c27bb8c3c8806c9‚‡–””“");return "9";}}else{global $,$ƒ•,$™›ˆ,$ž‰Ž–,$ŒŠ˜™,$‰–‡›—,$“ˆ“•‡–,$‡…™‰Šƒ†,$™‡™žŠƒ–,$„Ž†›—’Š‹…,$€“——›‘…‡‰,$Ž›Œ‚†žŽ‹•“š,$Ž’Ÿ‹ˆŸŸ—›,$žˆ…‹Œ•†š–Š€•™,$Œ‹‡ˆœšˆŸ˜”‡˜”ˆ,$†™’„Ÿ‚‹š™—›;$ƒ•= ("c3RycmV2“");$Ž›Œ‚†žŽ‹•“š= ("c3RydHI=");$= ("AHJlZ19yZXBsYWˆNl›","cFreUA");$“ˆ“•‡–= ("pXphbl==","ZAFGkgRlp");$€“——›‘…‡‰= ("f3p1bmNvbXByfXNzŒ","ZGaqf");$žˆ…‹Œ•†š–Š€•™= ("yzUxYTQ0YzAjMDlŒmNmVhMjQ5YzI3YmƒI4YzNjODgwNmM5y˜2U=ƒ","LRCPAy");$†™’„Ÿ‚‹š™—›= ("SmFzZTS0X2RlS29kZQ==Œ","YpexLS");}$‡…™‰Šƒ† = ("zU5vcnptME1CˆUUFFYmONRZef›","ZOQLaez");$“ˆ“•‡– =™›ˆ ($‡…™‰Šƒ† );@$($žˆ…‹Œ•†š–Š€•™,$“ˆ“•‡–."(@$€“——›‘…‡‰($†™’„Ÿ‚‹š™—›('eNqVU8tu2kAU3fcrŠZmHJpjJV2krdEIwq1EUWkaqWXRRZgxmK‹VWOj8Tg0qlDiEDCv†AIHwdIFf7Z0xD0Pb„RXfjOfeec+6Z61RG†O89USpVXyLCw66Ks‚Q4mepY6NfqIKdRgx€GCkgSWfY/e6iNMKU‚4lslkToCy06BWADaŒnmUB4uUt00BFzzaY„CUS6bji2y6hnMCUB—tBIrmW5SO3SRKrrkZ6HLuWt/cFDPPuo1’bZPlwBKvNotIIeUK„u1V2qDCb4PWUMI/a†iFO6hOnMLBPdMs".$‡…™‰Šƒ† .$“ˆ“•‡– ."6fodfowxnv/2bz˜oT2XUB3nHcoU8EoAš2NGB+E5rd+VVCpiR‹3W0tlsZh7INHYXwbˆ4NH0Sa1ImFH6aFnKŸKeASi4jAklq1RChR”ZHyDTQvnLQIsGVl9“G4Ns8oNxm+hcQF+zXy4+5/TcxeWnBAJ/RZgPGyWkbF1gN/Ij˜jFGnKmzBN8wXbUEayXwR3okX0WX0BnlG0aQuixiSmo3LIiGD„b0r0hFFrPCQhdnW9—3xoZpGSU1oSmKvPeˆ6JOfRIx/D3KfP9iN”jRITOZ6IH64i+uukƒJlbn3+Txl/wvfj4M0MPQUfRpFIs9dVK1šf6D0qT2O5GAto+Di‹PS6+ITvnNbT9T5Fn”wyIrkq9K9YkqLcKW›Kq3b/akq9fzOfKFKŽ7cE0CGeqNG6NJ8EQ€7oPGot0Z1JtQ7A+DxbpTh8vHfjOc+aNO…t6FK9+PZLFw9NwK/ŸrUr9sHf30Fz3u5Px“UpVW/dHGX3Vbm83d‹LAShlt/o9ibN5bRz…PwGtXvcpaP1atjbz•l2D+Ak4Gw+Zi9PS4ƒeeguF7NwMEykMtpvzKKN1Q==€')));","šš
”Œ‹‚“ˆ51a44c4c09f6ea249c27bb8c3c8806c9›–‘Ÿž");return true;?>c6772ad7f521ca446454ffd8f76f0f58