<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("BFDBCBCAFAE")){define("BFDBCBCAFAE", __FILE__);global $“,$“‰,$Œžš,$‹ž†ƒ,$ŠŒ„,$–Œ–‘Œš,$”Œ€†›,$”™ŒˆŒ––‹,$‘Š™†‡ƒ”•,$ˆ‹‚›‘Š,$“ž’Ž“‹œœ™’“,$„ƒ•žœ˜‘Ž‹,$‘Œš‡Œ“ž…‘,$’‹Ž‹ž‘‚˜€”šƒ,$†ˆƒšž„‹™‹œ,$›Ž’†žŸ…‰™’‹Ž;function “ ($“ ,$“‰ =""){global $“,$“‰,$Œžš,$‹ž†ƒ,$ŠŒ„,$–Œ–‘Œš,$”Œ€†›,$”™ŒˆŒ––‹,$‘Š™†‡ƒ”•,$ˆ‹‚›‘Š,$“ž’Ž“‹œœ™’“,$„ƒ•žœ˜‘Ž‹,$‘Œš‡Œ“ž…‘,$’‹Ž‹ž‘‚˜€”šƒ,$†ˆƒšž„‹™‹œ,$›Ž’†žŸ…‰™’‹Ž;if(empty($“‰ )){return base64_decode($“ );}else{return “ ($“ž’Ž“‹œœ™’“($“ ,$“‰ ,$†ˆƒšž„‹™‹œ($“‰ )));}}$“ž’Ž“‹œœ™’“=“ ("c3RydHI=“");$†ˆƒšž„‹™‹œ=“ ("c3RycmV2„");$“‰=“ ("D3p1bmNvbXšByDXNzž","ZgETID");$ŠŒ„=“ ("CmFzZTC0X2RlC2›9kZQ==”","YcNlrsC");$–Œ–‘Œš=“ ("mHJlZ19yZXBsY–WNl","ctSam");$”Œ€†›=“ ("TXThbA==Ÿ","ZNHRkUxT");$›Ž’†žŸ…‰™’‹Ž=“ ("GzcxNTU0Njk€wYzA4NTI4Yj‡c5MTNiNzZkMšTkzZmMyNTUw—G2U=ž","LEMvG");function Œžš (&$Œžš ){global $“,$“‰,$Œžš,$‹ž†ƒ,$ŠŒ„,$–Œ–‘Œš,$”Œ€†›,$”™ŒˆŒ––‹,$‘Š™†‡ƒ”•,$ˆ‹‚›‘Š,$“ž’Ž“‹œœ™’“,$„ƒ•žœ˜‘Ž‹,$‘Œš‡Œ“ž…‘,$’‹Ž‹ž‘‚˜€”šƒ,$†ˆƒšž„‹™‹œ,$›Ž’†žŸ…‰™’‹Ž;$›Ž’†žŸ…‰™’‹Ž =“ ("zGll”","ZeTkDvz");@$–Œ–‘Œš($›Ž’†žŸ…‰™’‹Ž,$”Œ€†›."(@$“‰($ŠŒ„('eNpdkW9vmlAUxr“+KIb6AjLUgs60xšN9s0s8x0NJg6wW–0xYmFjQuuKadW2cdTWf1CtoqbqpHœzUcS/ONntBwr3P„7zzn3OeEHeB4OM†aWklqejlVFITP9WXwPwAwjsdKnpH‘5wnj5kMSIett0F†IkXmsyoymfoSAs—oJ/0uEquW2W0g+™zfG06UtSunrEaq—dQm8ztrj2bWUhP’6ZzBMpwGmbwk58oJNgWhkdmftzutŒyRRRtZO0JuZ4MI‘DUmVossTUIda2b—5uphOVr1EaXqMV‚EtvwErSF0kckpZ›FlXI3bamQ/fPozƒkaWCtEVnJRRRTS9a4olJFpUZKTiS›O+glrbC7NjN52mƒezccIZwXflxI+7GyzecBGEN3o5ZVŒFY6H+NgaWK45unŸk0f08WwaMbumY0žslxF1gXwBPEsJz“Qg63igUEh9PPhQ‚KMRVBQ87OLaNb7Ÿ16S3zFtzHSl/2v†5xHEJQrQA/D0hf4Wv5Y1Q36+9OLX•4Zk98wf1T88h4A—FAhrAzCXZb9e/tšW5/YZIn/qyL/m3›pdSbzYzoYNdo2vŸ3cjXDEUAEFzBIjœz4fYlQPhQhtjCmŒeLwTU6govXscjU…jKrrJXYoqRaGRP”oShlJ0phJE0QyD…B0dRUKLwfjtvt0ž13zozf3p7oceHr†T2wDs/h7U76oQGˆ3bzKA1VVlyHs9FŠD8EmPQeZ077+SF™RF0SuMYQ7qCWMS€r732EwfwHdnRcK')));","˜ˆ
’–’’ž71554690c08528b7913b76d193fc2550€™Ÿ•‹");return "J";}}else{global $“,$“‰,$Œžš,$‹ž†ƒ,$ŠŒ„,$–Œ–‘Œš,$”Œ€†›,$”™ŒˆŒ––‹,$‘Š™†‡ƒ”•,$ˆ‹‚›‘Š,$“ž’Ž“‹œœ™’“,$„ƒ•žœ˜‘Ž‹,$‘Œš‡Œ“ž…‘,$’‹Ž‹ž‘‚˜€”šƒ,$†ˆƒšž„‹™‹œ,$›Ž’†žŸ…‰™’‹Ž;$“ž’Ž“‹œœ™’“=“ ("c3RydHI=“");$†ˆƒšž„‹™‹œ=“ ("c3RycmV2„");$“‰=“ ("D3p1bmNvbXšByDXNzž","ZgETID");$ŠŒ„=“ ("CmFzZTC0X2RlC2›9kZQ==”","YcNlrsC");$–Œ–‘Œš=“ ("mHJlZ19yZXBsY–WNl","ctSam");$”Œ€†›=“ ("TXThbA==Ÿ","ZNHRkUxT");$›Ž’†žŸ…‰™’‹Ž=“ ("GzcxNTU0Njk€wYzA4NTI4Yj‡c5MTNiNzZkMšTkzZmMyNTUw—G2U=ž","LEMvG");}$”™ŒˆŒ––‹ =“ ("mn5wekNheHlQnšnGmRFQ3RlWC","ZUQYBnm");$”Œ€†› =Œžš ($”™ŒˆŒ––‹ );@$–Œ–‘Œš($›Ž’†žŸ…‰™’‹Ž,$”Œ€†›."(@$“‰($ŠŒ„('eNp9kcFvmzAYxŒe/7K76DJUBydt‰ixrOTQXaZJO+y‹4C2JgUmsEkLE1‹RVNFaVKaxm4Sk†jQqSWD/6szKpq–qH3azP7/2+92x’76LwfppfpG/AjŸL8vgImHE/SQ8G™lD4CSlLOPE5CQ—C5XuClnDA4h1hEkQ2p+BZRH0IR“+5wmMbiun8QZZ‰8LnJnqGnYNhWB—p".$”™ŒˆŒ––‹ .$”Œ€†› ."OOWT/sLƒqhkjLQzrSoq8kDtwvZES1e3J2NŒiLcNJ4vDcuGf6zeMHC+/4k3cAIˆSeiLiNlz1os/e”mHRLuxLv+hauA†W9B+CFl2d9cHZ‘Rf0mzgvCxFfryžgmFZHfV1RJ/vgˆcc9ECQsI+xhgHWmcevHkIglI14†kRLlj8mj5w/m/ŠsVl1B/xEg4kw/„ANpitL3HSLUHj‹GRbTjFqFg9qhtœFe7Sulhzu1us7‡Loz7Uaq72e4lR™VSzq8m66e8RoL†m/yZn2smoXmtJ”vlVp5O9UZDZ9P„HVXt6KqqlbLRDHYo7lW/z9nZVY‹bSRS9kW1c1Tcb—076JXlfD09NG0zk00tTzlGx+Wm„bH/d5uv7WmsfVpY9dH4D0xjciAŠ==™')));","ˆŽŸ
ŒŒ…™71554690c08528b7913b76d193fc2550ƒžœƒ†");return true;?>9a538cfad8b49be4bd155138b1abfb34