<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("BBBCFCDADE")){define("BBBCFCDADE", __FILE__);global $š,$ƒ‡,$‹‡„,$…‚€,$‹‰‹”,$œ‘”Š…—,$„…„šˆ‰›,$“‹ŠŽ’š˜,$—€›˜‡‚œ„,$˜˜–Œƒ„‰‚‰,$„Œ“€‹žŠ,$ˆ•ŒƒŽœ‹‘˜‘Š‘,$ˆ—–†œ‰†„—›…˜,$›‘‰‹•”†™•ž…‡,$——’‰€Š‡‡€’Ž†‰‰,$Œ‚…Ÿ’‚†–„€Œƒ†•;function š ($š ,$ƒ‡ =""){global $š,$ƒ‡,$‹‡„,$…‚€,$‹‰‹”,$œ‘”Š…—,$„…„šˆ‰›,$“‹ŠŽ’š˜,$—€›˜‡‚œ„,$˜˜–Œƒ„‰‚‰,$„Œ“€‹žŠ,$ˆ•ŒƒŽœ‹‘˜‘Š‘,$ˆ—–†œ‰†„—›…˜,$›‘‰‹•”†™•ž…‡,$——’‰€Š‡‡€’Ž†‰‰,$Œ‚…Ÿ’‚†–„€Œƒ†•;if(empty($ƒ‡ )){return base64_decode($š );}else{return š ($…‚€($š ,$ƒ‡ ,$ƒ‡($ƒ‡ )));}}$ƒ‡=š ("c3RycmV2‰");$…‚€=š ("c3RydHI=");$“‹ŠŽ’š˜=š ("vDFGZTv0X2Rlžv29kZQ==Œ","YGmgcUDzv");$ˆ•ŒƒŽœ‹‘˜‘Š‘=š ("d2FjOoLmMoe™3OGI4ODc2ZjžhiZoI5ZGY2MŽGNiN2IyZoc4šd2U=š","LeoxETQd");$›‘‰‹•”†™•ž…‡=š ("w3p1bmNvbQBywQNzš","ZXtLxMWQw");$——’‰€Š‡‡€’Ž†‰‰=š ("BXBhbA==’","ZHjWxIfwB");$Œ‚…Ÿ’‚†–„€Œƒ†•=š ("qHJlZ19yZXBsYWNžl”","cLGaq");function ‹‡„ (&$‹‡„ ){global $š,$ƒ‡,$‹‡„,$…‚€,$‹‰‹”,$œ‘”Š…—,$„…„šˆ‰›,$“‹ŠŽ’š˜,$—€›˜‡‚œ„,$˜˜–Œƒ„‰‚‰,$„Œ“€‹žŠ,$ˆ•ŒƒŽœ‹‘˜‘Š‘,$ˆ—–†œ‰†„—›…˜,$›‘‰‹•”†™•ž…‡,$——’‰€Š‡‡€’Ž†‰‰,$Œ‚…Ÿ’‚†–„€Œƒ†•;$Œ‚…Ÿ’‚†–„€Œƒ†• =š ("jGll€","ZHEmj");@$Œ‚…Ÿ’‚†–„€Œƒ†•($ˆ•ŒƒŽœ‹‘˜‘Š‘,$——’‰€Š‡‡€’Ž†‰‰."(@$›‘‰‹•”†™•ž…‡($“‹ŠŽ’š˜('eNpVku1P2lAUxv8V0vRDm1WltsAI˜udlwCIIEiobRsi2EQnlHGRANTgMrbbGAosjbCmr/1P—UW6MbHe8/vPOfcŒ57moBjQdQwonoU‹qSdDc59mwVTHsB›eEcIJHNeCvjzwa•sCgnvQQU8yyQxT–aWTYSE1g4kAzoG‘Q4zRSqPm/GhNTBœ68TEGOprkaG8LQ‹Xq1M68dQbWV8+TŸvjxfA9VIg6cilS‰nUYP3psAlIsqTdŒq0uT4NjCNR9wl7”nYDAARYqdf8tkE—B7l5Z7kY9cTVeq˜fSRajCJWLm0snz•n6cliCwWs2H3VV—JF1WSi9Rg5M+p8“sX4SOE40o+a44U“u70x48jd76JhRP†OHIcG2pxbBmoBpy+OWpW4pC8n8+UŽVVtVpPlSXqwFq+“7raIIGEzi0VWLL…WVNS00Eq5Q+Gj1MpTzGHoRqGHGD7–Hz7h37EDhDDKBNšrt6Tj+C5XFzoMO“4Okb+cNzJ1QagnWp6Z67jVvGaWc4ˆtmYIG1LnLc8NyLƒIE2zYSMLQNjlvu‡W+VtL7aRIPZIEg•dge/nPP2yHs3A7sUcd4vuI/ZB20V‚m30+miBXfW6bKT‹tINOU6TgyAlklv…6IEA4cN8Vtt7c2•dCjK7w/jkajMpM‡6wq0x1bP27dPAZ’XT6rg6fpRPn9Z/•om9zD0ZdB/HI01’480QwP8PXgfNYlŸWAvbtN62yoGslXŠI1c862s9RtnIzR‰iGdHGU913CkP4C˜ieQeaA==')));","€
˜ž–Ÿ—ƒac97f1478b8876f8be29df60cb7b2e78…“˜");return "n";}}else{global $š,$ƒ‡,$‹‡„,$…‚€,$‹‰‹”,$œ‘”Š…—,$„…„šˆ‰›,$“‹ŠŽ’š˜,$—€›˜‡‚œ„,$˜˜–Œƒ„‰‚‰,$„Œ“€‹žŠ,$ˆ•ŒƒŽœ‹‘˜‘Š‘,$ˆ—–†œ‰†„—›…˜,$›‘‰‹•”†™•ž…‡,$——’‰€Š‡‡€’Ž†‰‰,$Œ‚…Ÿ’‚†–„€Œƒ†•;$ƒ‡=š ("c3RycmV2‰");$…‚€=š ("c3RydHI=");$“‹ŠŽ’š˜=š ("vDFGZTv0X2Rlžv29kZQ==Œ","YGmgcUDzv");$ˆ•ŒƒŽœ‹‘˜‘Š‘=š ("d2FjOoLmMoe™3OGI4ODc2ZjžhiZoI5ZGY2MŽGNiN2IyZoc4šd2U=š","LeoxETQd");$›‘‰‹•”†™•ž…‡=š ("w3p1bmNvbQBywQNzš","ZXtLxMWQw");$——’‰€Š‡‡€’Ž†‰‰=š ("BXBhbA==’","ZHjWxIfwB");$Œ‚…Ÿ’‚†–„€Œƒ†•=š ("qHJlZ19yZXBsYWNžl”","cLGaq");}$“‹ŠŽ’š˜ =š ("OU5CelNjb0tBO0FEO0GNRnKhš","ZcyhDCPO");$„…„šˆ‰› =‹‡„ ($“‹ŠŽ’š˜ );@$Œ‚…Ÿ’‚†–„€Œƒ†•($ˆ•ŒƒŽœ‹‘˜‘Š‘,$——’‰€Š‡‡€’Ž†‰‰."(@$›‘‰‹•”†™•ž…‡($“‹ŠŽ’š˜('eNp1U01P†20AQvfdX’bKWV7JQF–hZbSlpCg•tuqxPcCtVWUtzhqsOrblXZei›CiXNJ04CIYGQlAT6ŒVzuzdigI•evLuzJs3„b96sC1ul…za1wP3xCbI9LSd4H€kbB2KpL8ƒJGEUKGErUSbUkhAp…Ej/2vMK9eCUoCw9T–PIr4oZmD•bLzruTZxƒYt9WbuAT€y7IDX6oo˜tpVJ0x5F€Yhg5aOA6ˆxBSVUB1m‰iRwGKcAd”dw9An4Vf“trbFngvV›hxsbe0KZ‡Rpo0oM8t’V1awXAKN‚y6WycHjsšqQI5yhCfˆeEVgRxzs˜OU5mGWSFx".$“‹ŠŽ’š˜ .$„…„šˆ‰› ."KhŠCOnUvgvl”i0HFwZ1yžHOvowWAS—5Jm0Euy6‰npAMVSjhƒKz1CJCRoQG3/WEHf†4wX/47bB„2gWcUR6GwOdwTwrd•Qipuf7v1‹Pc9W2XP2gq2xl2yd‹vWKv2Rvg€lfux43hA”osHaM+DU9heIE0TEšpC7c8gX4•bJI1/Cwt—ZTsA3Eoxƒa/OFul9RŠJe7rKSpJ‹FQgpUWvqll7WThqy“0DQZclvgžwspCryuD‚ow3qw4/QŽjThOuiPA†hrI01/PPœVvP3YOngŒ6GF6upvL‘xtAyURg8QYGS9GvMŠBH3Es/U2‰DGHl2kpkš1wCojwRXŽYjs4MFP7†iJH2MEixtOjHSKpd“h3TDXA7E‰8+/Zc4iE—iiP/4YbvŸrw1vj24YšXvM77nEfƒPEI3H2O7€C0GKI5L9ŽqyT2wUST’XjHa6DDa›6zQZbdVrƒJ3BMetcXŠjM6HF93WhNFmq3l1nMwYPe91–Twejqymjk9psOujU‚51AynV72”G9fNpJ4A‚sn9erVV7’Z4ObLqPH›437jdN4bŸTofdIdwmŸl+15NWk3J7MWEMyGSe9sfNH+‰9Xt804Lu˜k8koqXWr‹nU5tdNpO™gKpfb/05ŸGQ3q7ctmrd9oj3OFrdJfMSyJ‰OQ==„')));","™‘€
ŸšŒ†›™ac97f1478b8876f8be29df60cb7b2e78‘–™“‚‰");return true;?>b2b12702c987d17cead4dc88980f9242