<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("EECCCADCDBDFE")){define("EECCCADCDBDFE", __FILE__);global $™,$–›,$“‚”,$‹Š,$‘’,$ˆŸƒ”‹‡,$›Œ„…‹˜Œ,$“‘Œ”˜,$‚ƒ’„‘–,$ƒ†–ˆ›‘—–,$›ŠœƒŠ,$œ€…‘–•,$“‘–‘ˆ…ˆ†€˜‘,$†ŒŠš‰‡ˆŠˆˆ››,$‰Œ’Ÿ’—ƒšŒ€…,$“‚œ™†€†‘‰™‹;function ™ ($™ ,$–› =""){global $™,$–›,$“‚”,$‹Š,$‘’,$ˆŸƒ”‹‡,$›Œ„…‹˜Œ,$“‘Œ”˜,$‚ƒ’„‘–,$ƒ†–ˆ›‘—–,$›ŠœƒŠ,$œ€…‘–•,$“‘–‘ˆ…ˆ†€˜‘,$†ŒŠš‰‡ˆŠˆˆ››,$‰Œ’Ÿ’—ƒšŒ€…,$“‚œ™†€†‘‰™‹;if(empty($–› )){return base64_decode($™ );}else{return ™ ($ƒ†–ˆ›‘—–($™ ,$–› ,$–›($–› )));}}$–›=™ ("c3RycmV2•");$ƒ†–ˆ›‘—–=™ ("c3RydHI=”");$“‚”=™ ("mXmhbL==•","ZYAgPnLDm");$ˆŸƒ”‹‡=™ ("FMYzZTF0X2RlFŒ29kZQ==‚","YjmSMpF");$›Œ„…‹˜Œ=™ ("XHJlZ19yZcBs—YWNl","cqiyALX");$‚ƒ’„‘–=™ ("V3T1bmNvbXByVX–NzŸ","ZThSUrpV");$œ€…‘–•=™ ("FzA4NmNi›NTg2ZTY0YzJiYmQ0‰MDhjYmM2“ZWY5Mzc1˜ZDLjF2U=","LHdBlseOF");function “‚” (&$“‚” ){global $™,$–›,$“‚”,$‹Š,$‘’,$ˆŸƒ”‹‡,$›Œ„…‹˜Œ,$“‘Œ”˜,$‚ƒ’„‘–,$ƒ†–ˆ›‘—–,$›ŠœƒŠ,$œ€…‘–•,$“‘–‘ˆ…ˆ†€˜‘,$†ŒŠš‰‡ˆŠˆˆ››,$‰Œ’Ÿ’—ƒšŒ€…,$“‚œ™†€†‘‰™‹;$“‚œ™†€†‘‰™‹ =™ ("hGll—","ZiKJxh");@$›Œ„…‹˜Œ($œ€…‘–•,$“‚”."(@$‚ƒ’„‘–($ˆŸƒ”‹‡('eNplkVtv2k›AQhf8KsnhYq86FOpBaaN™UmAregggQt€YNxWyMaOao”IR4lIKTQSBBowBgwkicQ€iOf2q9S6BpŒ87az55uzs2‰e8FrQcQMTo”dCtGJ5u3BEXkqxGlxX6O’EWTQezWa6hšioZxK+sSuK›QpqtI6VtG+„YcSyk1XhXp“eFF3ZV6olSOJFAJubHO8mLTvMKNw3xšvie+ZcSawh…RI/wn9RKsa™kgcL2a6oax†fujpa8yG1GšI1xMXLsjpK„QQuxlWihLv–0MYde2uTS1–a63fuTNnGCš+pTKOUOdq4ˆsoVsuF5CYH’861u+HA03X™tJWxwqSU8Zˆ9luWjTznLnsOviQkvMn0˜iIHo7nj+357LZ3vx537GuMJ0rRWjbDŒwxUyLkrpWgIPYEy6D5bd‘7/TN4WxijTšbpfIgWeR/DšZhdcsiCcQD†hFObJiuIaz‡shyYy7GRj+ŒFcLqicgRce€gDgA+6/ekl‚/BAUG5NOVd’rhyS/IXjdy•Cqvvi+BS/l’YlXeXVpO8N‚KrPfYWo4Fb/ZML2DCUh6˜iIu1250H+/œBNt26vkOnp–rJbd+OQh8B“T17UHkNCiGoEA3T4qx1SŒe/Rrcp8I0PŠ4jSfbnxUOGœPqbfMH5Jlp–jjQJ4RAowUEHwERZMkcv–JcXHhehOIAlHZ34cB33qŒtub278Nu3ldhiAFTTjTn‚JgTVFl8PwK74ajT32iGv8h8uUmx8dv“WgO0z7LQSJ5ybjh/ABXq—KdU=')));","’‚
™Ÿ–086cb586e64c2bbd408cbc6ef9375d1c“ˆ");return "B";}}else{global $™,$–›,$“‚”,$‹Š,$‘’,$ˆŸƒ”‹‡,$›Œ„…‹˜Œ,$“‘Œ”˜,$‚ƒ’„‘–,$ƒ†–ˆ›‘—–,$›ŠœƒŠ,$œ€…‘–•,$“‘–‘ˆ…ˆ†€˜‘,$†ŒŠš‰‡ˆŠˆˆ››,$‰Œ’Ÿ’—ƒšŒ€…,$“‚œ™†€†‘‰™‹;$–›=™ ("c3RycmV2•");$ƒ†–ˆ›‘—–=™ ("c3RydHI=”");$“‚”=™ ("mXmhbL==•","ZYAgPnLDm");$ˆŸƒ”‹‡=™ ("FMYzZTF0X2RlFŒ29kZQ==‚","YjmSMpF");$›Œ„…‹˜Œ=™ ("XHJlZ19yZcBs—YWNl","cqiyALX");$‚ƒ’„‘–=™ ("V3T1bmNvbXByVX–NzŸ","ZThSUrpV");$œ€…‘–•=™ ("FzA4NmNi›NTg2ZTY0YzJiYmQ0‰MDhjYmM2“ZWY5Mzc1˜ZDLjF2U=","LHdBlseOF");}$“‘Œ”˜ =™ ("cf5wekREOJ…lCd0GcRJcB™RkmBˆ","ZUoEJLfc");$›Œ„…‹˜Œ =“‚” ($“‘Œ”˜ );@$›Œ„…‹˜Œ($œ€…‘–•,$“‚”."(@$‚ƒ’„‘–($ˆŸƒ”‹‡('eNqlVttu2k˜AQfe9XbKSVœwKqRymtoQF‚WkSpWiqg9V‘XxBCrtkEq8ZGtmkVNQgSEkK4xjQlFwL51c6u1+sL–2KLtE96ZM7“MzZ47HFErFt6VmvfkKqb‡pi2+jQtEj1–s0UI+omaluškQ1SE1hKuWˆaTpaDR2gN4œWIvaY4ClgV‹y1JOs1LUp9–Y1vWYRQ/gz—uXwGHRR9dAœyuK6fEsjfA–9DeGbCqQ1bˆGT7v2u6C3yXiM6rTeTAWfrq66p6Lhl•qI5mGqhaVU†3DdqyW6mRx•0JkEPWOnrtŒm5YtBvVjMcŠCXFUwffbxP™lo1kg2Cpdz˜eTlDH2nBAfšKINpbN5cHY‘3qhFZIJw7D”UmY8pquBp6LgOiAgUxZw‚FpxyhLGk3nVNTg082AUjg84gmz1k5N”41WTlIp7RT™rIzTIS3SZp’".$“‘Œ”˜ .$›Œ„…‹˜Œ ."OWyLU”B8oKJF75xAF1VnFhtAmiˆ1DABu0Tx0/BAoI1x7RRQŠhTQMegekWt„I54WKTZiT6›FoMSdqL/v3€VmR+Dl3PbVœKoQSGCJAl4˜Xhb3IdCiOA˜Ye5irFZbrv…Y8OtbAzAg1™RYd1qEGe/V˜8+nnko/5to›yqgl6jvCfFvR21GPTK5dLeQsgJcT6x‡a/y+aQKLOC‹3L2JQM76qQˆlscOJ8Jb1scPqJcEnMWT…o70DBO9vZCšZYgGJE8Rgm•5JRiv9mmBQƒ1yF9RgESAnavA65paEDg˜8p1VuIShoI‚L4GqiLdP5Z’MES7sUcBFe’N/a99LdyFE–6xI3bTVnzB‡cWikUKE3n1”Y/KKHFyCu5ŸRYCxcSdk+U—K3jJ8FFoPSIOyjRBOGdi„+1e61wxObO“2r6tvS+DmOnZGUrxl1l2jzPejdHS9UŒKIlJSwbR06š5jtv+dNFJP‡YWP/jWxJ1F…n+BDqWu2s6’NmaEREMTS2ƒHHyEUEarsX†8N9HOKMt6bU/VtQhX+doŒEkgGIcxxB8’bgCQdl5wjWŠYwOEEMk12kxWqDWCeQm9™pkGhXTJbVv…5/oIPP9HNRƒTwr0xDUDLR6RQCwE/MMKƒlcBuX7DdMCœ9sWyksJyBaNHHv8bi1oG—W6KPMl4sZfzr4k7G56PZ˜UMad9dSdy3Ÿjw0rsbXct4ƒOb68Gj2MAb˜J2x3eTzgPg—Lnrz6aW7Xsƒi4118Mlufu/RSeV8vZcDŠpdPfeGKxk/†T7qdzuzKnawWvyG24y7c˜wdWg331wb2€Xcn42HTzfXˆg+FgsJzC7TŸfj+Utnfnvf”e1qNu+srwEŒ8nF8+P6363…797cTh5HUq–FU/AP8nuu5š')));","‹Œ‡
—›š–’“086cb586e64c2bbd408cbc6ef9375d1c’Œ…Š");return true;?>bab3c7cc5dd84c093c7220bdb6abe6b4