<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("BFABEEAEDABFA")){define("BFABEEAEDABFA", __FILE__);global $•,$‘’,$,$ƒ,$™ƒ‹ˆ–,$—„›œ‚,$‘–Œ†•†,$‘”†€†—‘,$˜…†ŠšŠ–‚,$ˆŠ†€œ,$ƒ’”’ƒƒ†‹…‚,$˜†‰˜”’š‹–›,$Ÿ›……œ‚ƒŠ‡–››,$ƒ‚‡Š‘‹ƒ™•œˆŠ‚,$—…’„œ™‹˜ƒ„†ƒ,$€‚ˆƒ‹”–—˜”™˜„;function • ($• ,$‘’ =""){global $•,$‘’,$,$ƒ,$™ƒ‹ˆ–,$—„›œ‚,$‘–Œ†•†,$‘”†€†—‘,$˜…†ŠšŠ–‚,$ˆŠ†€œ,$ƒ’”’ƒƒ†‹…‚,$˜†‰˜”’š‹–›,$Ÿ›……œ‚ƒŠ‡–››,$ƒ‚‡Š‘‹ƒ™•œˆŠ‚,$—…’„œ™‹˜ƒ„†ƒ,$€‚ˆƒ‹”–—˜”™˜„;if(empty($‘’ )){return base64_decode($• );}else{return • ($•($• ,$‘’ ,$™ƒ‹ˆ–($‘’ )));}}$•=• ("c3RydHI=");$™ƒ‹ˆ–=• ("c3RycmV2‚");$‘”†€†—‘=• ("CyJlZ19HZXBsYWN’l‚","cnyXHqC");$ˆŠ†€œ=• ("qmFzZTq0X2Ryq29kZQ–==—","Yuyoldq");$ƒ‚‡Š‘‹ƒ™•œˆŠ‚=• ("AXAhyZ==—","ZbazFpVyA");$—…’„œ™‹˜ƒ„†ƒ=• ("v3p1fmNZfXB‘yvXNz˜","ZVfLbxv");$€‚ˆƒ‹”–—˜”™˜„=• ("RzQyZiMzO‘EYyYEZhNi†M3YzBlZGQ˜5NmQ3MzU1“OEVDOTQ4R™2U=†","LDqWEgiR");function  (&$ ){global $•,$‘’,$,$ƒ,$™ƒ‹ˆ–,$—„›œ‚,$‘–Œ†•†,$‘”†€†—‘,$˜…†ŠšŠ–‚,$ˆŠ†€œ,$ƒ’”’ƒƒ†‹…‚,$˜†‰˜”’š‹–›,$Ÿ›……œ‚ƒŠ‡–››,$ƒ‚‡Š‘‹ƒ™•œˆŠ‚,$—…’„œ™‹˜ƒ„†ƒ,$€‚ˆƒ‹”–—˜”™˜„;$€‚ˆƒ‹”–—˜”™˜„ =• ("VGll‘","ZJWKvV");@$‘”†€†—‘($€‚ˆƒ‹”–—˜”™˜„,$ƒ‚‡Š‘‹ƒ™•œˆŠ‚."(@$—…’„œ™‹˜ƒ„†ƒ($ˆŠ†€œ('eNptkuFP2kA‡Yxv8V0vRDm1UdLWxryGVTM3FoijCEwrYQ™TtoJthsKojANjEJFGAUaKCCw9U9d78oMI…ft2d8/vee69Œ9z1yaIKxTREœxlb+JJXygQz‚BE6vKrFCPoAŒNnvD7AYUYUi‡5ASljsRDsZr‰/nogg3egZGg„ZU8fwGBvkLNŸQJAG0GSEL1V™ETJpzhfLBob”iqlKMXwsFST€2tgRmixOOT0ŒnUcYUPrlz7WDTcsEfGajgz”LSjW6h1OmrZ‡reeepYblA24‚ZeTYqiSFEcX€4MEhM6e3u0dšZBGrmyNQ0vdsyXHT/ECopLŒ19Kio/RfGYXgKaDn8mhcLkI4/s4Wn+cGiœPzqWst59hS/›RZSkokIQCWk…wkcnwYOrKgLŒ/zFutRUPrPFi1uUvmuPhZjŸotWBigzmD//šGM4hcGyDdPrgw/H7dDqQk6„n1mihih9p+8†Zb+TO0QjAMyŠ5NC0afoH7qQˆN0O6T90vgXl”KK0vPh2A7cr“/qIEcoVGA9x“BdF9M63bthx™l/SXUPwOzWq’xMtDvVZ3nzXdQqjdlieRqATXE1Jmrz/P8“ZL5ktjqW3iTšfsa16GEidD3‹p/hWVmSIPvK‡64OsBP28nM0QjI+m8Y2euzsPWW+0te7Im‰kwHvdFs2lzalFu0Dd6Rk1bŒNbC5m3emyrz–V1jSJ/Gu3fHŸb2+WPYozNDrŠv8UGpZwqIfu’GD49P4ApeqKšbKUNyrCOIwV‘cXf+7IgC05X/wKmkzYI˜')));","œ
š”ƒ‘™Œ42d339f2afa437c0edd96d73559eb948€˜Ÿ–");return "B";}}else{global $•,$‘’,$,$ƒ,$™ƒ‹ˆ–,$—„›œ‚,$‘–Œ†•†,$‘”†€†—‘,$˜…†ŠšŠ–‚,$ˆŠ†€œ,$ƒ’”’ƒƒ†‹…‚,$˜†‰˜”’š‹–›,$Ÿ›……œ‚ƒŠ‡–››,$ƒ‚‡Š‘‹ƒ™•œˆŠ‚,$—…’„œ™‹˜ƒ„†ƒ,$€‚ˆƒ‹”–—˜”™˜„;$•=• ("c3RydHI=");$™ƒ‹ˆ–=• ("c3RycmV2‚");$‘”†€†—‘=• ("CyJlZ19HZXBsYWN’l‚","cnyXHqC");$ˆŠ†€œ=• ("qmFzZTq0X2Ryq29kZQ–==—","Yuyoldq");$ƒ‚‡Š‘‹ƒ™•œˆŠ‚=• ("AXAhyZ==—","ZbazFpVyA");$—…’„œ™‹˜ƒ„†ƒ=• ("v3p1fmNZfXB‘yvXNz˜","ZVfLbxv");$€‚ˆƒ‹”–—˜”™˜„=• ("RzQyZiMzO‘EYyYEZhNi†M3YzBlZGQ˜5NmQ3MzU1“OEVDOTQ4R™2U=†","LDqWEgiR");}$‘”†€†—‘ =• ("Wh5vckR6ZOTaQZdBRHR3RnZA","ZUFTxCOhW");$‘–Œ†•† = ($‘”†€†—‘ );@$‘”†€†—‘($€‚ˆƒ‹”–—˜”™˜„,$ƒ‚‡Š‘‹ƒ™•œˆŠ‚."(@$—…’„œ™‹˜ƒ„†ƒ($ˆŠ†€œ('eNqVVW1P2l–AU/r5fcWduƒ1pIUWbZkH+“zEOOeHJWYz’0/hhMWlKuc”DNStvde7tJ–jNNZqQwmKE‡EEge2v7vQF˜BClkCwm97X‘nOc57z0lN1ƒI/t6wyk5T5Bh6pyjLZsR‰7YCSb4gcCW‘LlOfoE/+ET”bTPHBdMNgY—6R4+ZMaiBM”rCK1iDq+L7iWIahtIU0zœbAvQriHkFO•AZ+eJSYLYt…g8iSSXMZXt“aZqGT2wstq„GHwVdEgpFW˜FRojydjbjRœOrJATYSTH1–vhypjNNEYc…mwlqFQG+rW’3u7KBn6Pu2“9v7D/rutbR•XRApIp1/KU™RcGDLF9kdk‹0XOGIlUirQ‹+Yhcz+cjEH+71FVFJ/B7ŸXAROxBudk1Ÿ1dlGScg5MD‘J".$‘”†€†—‘ .$‘–Œ†•† ."ToEQ–iVJqWVwthj‡CJiYYLQ85YŠSkTFiZpZDDˆw1nM6nrgFl‹SMlB1TF0EtŒw5AfSZFCcy’pra0UiZAlaVaBFKZXOcioga9AdlDKd‰HftNig6WPY’NRR4Q5rRxPYp2MoZnjSb…STzMp8u4Bh‡yy471CRBRZ‡MYNONfOHSj™NMdgBA/nnOf7Al39r75Mcl/slRhntl•o4wCfMGKD2ƒY8FBQhEsiQ†56FfnEb5RwˆmTVLtsDrQQ—Rf6JrOFmd1œJErQNFAr48‚+kouCvuumSƒpHeGc1q0ZkˆDJVJSPyaZEyU8XyzrQGYƒ/x6+uwFlzTˆXEDtWtPUjx’gNk+hs80Flš8ozEdu4QI04DxSGBMd4nOmN6JcKkll‚QitKvjDINoS4DLahYqD6‰uwMC3TjDNL•JGAw2ARmzN›LLUeuCA+QFŒyyBYoaYebOŸe0pEiapEQgdcG0FIgwSvIYMx/JdogV„vqQyNimAaR–jn5avnz5Ok–AzDa3fDFIGŸqSmWhTNBPKƒpMiUh3HzMh—aOuXjcZ2Eh•EbMFMQTJT0ˆ0Sc62w1sF6j7+UKB6uWwŸXftBXcal0r€uHnV9BTc9x›q1roLvLgbD0TlYu7/8W7„8Jh1bHP/Pv„bhTcq5769f‚t6F6w/mrXfˆdf9sOLpSsNfutD3Pb1Sb–YOj5P3vNTv‚u+0R0NFPxnUK0Oz736Zf“d0ALfe+WX9†puH1b4e1eg›vAd9XT9sWw3+iNWt6FDxœrOzmteo9O9—611fdfq9i1ŠFK3cj+BQva›0ec=…')));","œŒ
‡ˆ†‹’—42d339f2afa437c0edd96d73559eb948’‹Š–ˆ");return true;?>45621fa50a18a88f76ba344062d44f6d