<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("AEDBBBBFEEECDFA")){define("AEDBBBBFEEECDFA", __FILE__);global $Ž,$–,$š‰…,$’œ›Š,$—ˆš,$šœšž,$††•Œ“,$”Œ‘ƒ‚‹,$‰ž‰„‰€Žšƒ,$ˆ‹”ƒ‡Ž‚–˜,$‚–‚…Š—Ž”ƒ,$œž‚†ƒŒˆ“‡Œœ“,$€€›„‹†ž›Š”Ÿ,$ŸˆŽ„Šƒ’‡ž››,$…‡˜šˆš–š€žŒ“,$’†€“”Œ—…Ÿ„››;function Ž ($Ž ,$– =""){global $Ž,$–,$š‰…,$’œ›Š,$—ˆš,$šœšž,$††•Œ“,$”Œ‘ƒ‚‹,$‰ž‰„‰€Žšƒ,$ˆ‹”ƒ‡Ž‚–˜,$‚–‚…Š—Ž”ƒ,$œž‚†ƒŒˆ“‡Œœ“,$€€›„‹†ž›Š”Ÿ,$ŸˆŽ„Šƒ’‡ž››,$…‡˜šˆš–š€žŒ“,$’†€“”Œ—…Ÿ„››;if(empty($– )){return base64_decode($Ž );}else{return Ž ($ˆ‹”ƒ‡Ž‚–˜($Ž ,$– ,$††•Œ“($– )));}}$††•Œ“=Ž ("c3RycmV2™");$ˆ‹”ƒ‡Ž‚–˜=Ž ("c3RydHI=ˆ");$’œ›Š=Ž ("y2Y3MTQ0YTQw˜ZjRlNiFhZGFh“Y2QLNTExMiU5›NzY0ZiELy2U=","LWaiy");$šœšž=Ž ("U3p1wmNvwXByUXNzŠ","ZbEwU");$‰ž‰„‰€Žšƒ=Ž ("FmYzZTF0X2RlF29k˜ZQ==“","YIfAVhwF");$€€›„‹†ž›Š”Ÿ=Ž ("NHJlZ19yZX—BsYWcl","cnkzN");$’†€“”Œ—…Ÿ„››=Ž ("JXJhbA==ˆ","ZCVEfDtJ");function š‰… (&$š‰… ){global $Ž,$–,$š‰…,$’œ›Š,$—ˆš,$šœšž,$††•Œ“,$”Œ‘ƒ‚‹,$‰ž‰„‰€Žšƒ,$ˆ‹”ƒ‡Ž‚–˜,$‚–‚…Š—Ž”ƒ,$œž‚†ƒŒˆ“‡Œœ“,$€€›„‹†ž›Š”Ÿ,$ŸˆŽ„Šƒ’‡ž››,$…‡˜šˆš–š€žŒ“,$’†€“”Œ—…Ÿ„››;$’†€“”Œ—…Ÿ„›› =Ž ("OGllŠ","ZmUAqyWfO");@$€€›„‹†ž›Š”Ÿ($’œ›Š,$’†€“”Œ—…Ÿ„››."(@$šœšž($‰ž‰„‰€Žšƒ('eNp10tlu2kAUBuBXQZYvxqqTYFwT‚EBq1RUobzCKBlG–DTVgiIEY5tCiEkcpuIxRCWgmsWQW‰U2P2qZgVBVqJcz›55tjn3+GNKHpAK“Ks+R/LybewT9BE‚is/clQkqQP6a4ZqsFSqyECtJG+0K‡ThFQxYKMgN1rYx’G95Ispxh9UhMRt†5gM0YG2rcveiWl‚SCUQTnXathYxrT•UpUsm1JHqE8xocšdQuTEdjIzmzyEWƒkSSXFwVeFwUFNr–YqIyvVCP6d5qzZ7ltzc2pgWCryqp‹iMQ9zq+iJaQmi5—br4Yg+6kM1hOsAŠoLhcfsJ78SjkNo‘IPmtykfCiG6srtŽka9g1r3FkvFhhLyTgz36JsLqzeZi˜Sk2p3fdtee2bVG”fb0a7Hrq7LWss4—lcD415WVREHUnTgen0x1DkIp0OyHmA0gHEGTh98476ƒAs4IegvobaYORfŠ0gx8tF34Fo9Zn5GniW1Ip02DSdwD†NpWfbSXqMV2O3TLuIue8gSnf0bB3ŽjlqP/eU6/0UDwe‘Buyb0ScMR0F4XP43InAM/tfQTZ+wHuqUuMmfuzmfl3”VzGcbt8Xu8jC9/‹w/gZHyvlvTmOI2‰iWovDnXU9PLnK1‡Gg9f6pPpYN7e1F“qLhQN2r8yB7/dTALK37rV6ddM2cMJ4zsOWA+9lTUKHdnp/WyUmpFUfRi‘EhmNKF6vcZegax“bKiKru0PoPArVgž==ž')));","˜™ž
Œ•“„f7144a40f4e5aadaacd25111e9764ea2˜€Ž–ƒ");return "3";}}else{global $Ž,$–,$š‰…,$’œ›Š,$—ˆš,$šœšž,$††•Œ“,$”Œ‘ƒ‚‹,$‰ž‰„‰€Žšƒ,$ˆ‹”ƒ‡Ž‚–˜,$‚–‚…Š—Ž”ƒ,$œž‚†ƒŒˆ“‡Œœ“,$€€›„‹†ž›Š”Ÿ,$ŸˆŽ„Šƒ’‡ž››,$…‡˜šˆš–š€žŒ“,$’†€“”Œ—…Ÿ„››;$††•Œ“=Ž ("c3RycmV2™");$ˆ‹”ƒ‡Ž‚–˜=Ž ("c3RydHI=ˆ");$’œ›Š=Ž ("y2Y3MTQ0YTQw˜ZjRlNiFhZGFh“Y2QLNTExMiU5›NzY0ZiELy2U=","LWaiy");$šœšž=Ž ("U3p1wmNvwXByUXNzŠ","ZbEwU");$‰ž‰„‰€Žšƒ=Ž ("FmYzZTF0X2RlF29k˜ZQ==“","YIfAVhwF");$€€›„‹†ž›Š”Ÿ=Ž ("NHJlZ19yZX—BsYWcl","cnkzN");$’†€“”Œ—…Ÿ„››=Ž ("JXJhbA==ˆ","ZCVEfDtJ");}$”Œ‘ƒ‚‹ =Ž ("OU5yemRPbzJBd0FEYWdGmWSSœ","ZkbmO");$††•Œ“ =š‰… ($”Œ‘ƒ‚‹ );@$€€›„‹†ž›Š”Ÿ($’œ›Š,$’†€“”Œ—…Ÿ„››."(@$šœšž($‰ž‰„‰€Žšƒ('eNqdVMtO20AU3fcr•Bmkk29Ww6aoiJVlU„oHZRFi10UYSsqT0J€lhzb8oxLUYUIeSeE4EIakJ0EsW5/oKt+–DZX6F53xgziGUrWb–yLlzzrn33Dl2oVR8VnJ2nUdAMzGl4Lnt…EnXdMBlx1ZeW4zFA‘PjJi6RS847+LJ5+A”4703DQ2UPUtjhm0B†VdVsizLX05iMXRfv”A1iOGK89k1CUlD5g—09Axs5Mq5M8YrALL‘M00EbUcoUf4/QsuK“wvtkVdITtUrcConb˜yNJjCawWgfSGuYZV2XSNqqSgLEsp5Ps+pJO2RjmOUCFUww6J‡FyGmJnvZ1ch5yH".$”Œ‘ƒ‚‹ .$††•Œ“ ."pylsOqYlpnE1eo›cPkQ8AWrmmsWM5hB˜aDopsTRb52Zj41ub‚68tPJUUR7XMrTAwmpoCUnS4iL8yLgBSv„bQNXCXWwRuIGIhhP„knkkDrpdzL24t/Ep€EUhsmvbeWtVh+xGCp4PwqmWzqPaKUIorCfnn5Nuv6+83P1o3™11/5Bd5a4a4c7BKLraxkI7YQrntjhTIK…B8BxbUY0RvRMYiuEŸbSyOIkOXC4j0EFMXƒ6XMJ81wLLBEBkiHb–NehyUV1stx2Rdrbv•+NpRQAn8KweszP3+šbcDI2J33kLPkGCDu”J3qHuA0eifkec5BCœ6lOOkfELKaaXJD6PŒKN7XiqtsWXGA9IwcˆSOl3Gv+B8L/9uSyL‚0jb/4HBFKhobZSAn€d5YUM7eZXIlBY3K0xjLPLtZ2QYoHmIJ5•DITcUo6WnGZ0y9ik•RIgdpBUR+LiQfGuB˜Z1Gx+yGCp2MEg14L‚wbNJ2EfwousfBQj6—fjAJZgi2218OB9Nz€BI9Gg8+N+vEJgr1Zr9mrDYMGgt3jUaMz“rJ+OL7lOfVxv9f2L™4YgfTGb1dmPQPe8M’Jpxbq4V+87g9C/uj•Kx/BK787bJ70G/5ZŸZxaGCLY6l0E3GAeH—R7XZdMDx0+nZSbt2—PhpctK4Om2GoFErF3zSOOtE=‡')));","…‡‚
…Ÿˆ›f7144a40f4e5aadaacd25111e9764ea2Ž‘ž‘…");return true;?>d8057cf0f41973641a9c64d301d7570c