<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("BEFABDFAEFFB")){define("BEFABDFAEFFB", __FILE__);global $†,$”œ,$Ž˜•,$†Š„ƒ,$†‘ˆž,$ˆ˜™“€™,$†‘’“‹™,$˜‘•†‘Ÿ,$‡–Šš’Œ›,$œ•”•ˆ–Ž™€,$‚ŒŒœ…Ÿ’……„•,$…ŒŒ‘š†ƒ˜“”‰,$”Š“‹š„„›‡’‡„˜,$‡˜ŸŽ•”‰…„‰Šž,$žŠ“‡ž›‹˜€“‰‚œ,$Žœƒ‡›’„‘‡”•ž™“;function † ($† ,$”œ =""){global $†,$”œ,$Ž˜•,$†Š„ƒ,$†‘ˆž,$ˆ˜™“€™,$†‘’“‹™,$˜‘•†‘Ÿ,$‡–Šš’Œ›,$œ•”•ˆ–Ž™€,$‚ŒŒœ…Ÿ’……„•,$…ŒŒ‘š†ƒ˜“”‰,$”Š“‹š„„›‡’‡„˜,$‡˜ŸŽ•”‰…„‰Šž,$žŠ“‡ž›‹˜€“‰‚œ,$Žœƒ‡›’„‘‡”•ž™“;if(empty($”œ )){return base64_decode($† );}else{return † ($†Š„ƒ($† ,$”œ ,$‡–Šš’Œ›($”œ )));}}$†Š„ƒ=† ("c3RydHI=š");$‡–Šš’Œ›=† ("c3RycmV2›");$†=† ("fmFzZTf0X2Rlf29œkZQ==ƒ","YEubf");$”œ=† ("gHJlZ19yZXBs„YWNl”","cktLhug");$Ž˜•=† ("C3p1bmNvbXUyCXNz“","ZBbUC");$˜‘•†‘Ÿ=† ("CXChbA==ž","ZYoGcC");$”Š“‹š„„›‡’‡„˜=† ("CzY0OWQtYTMŒzNDdhMDkyZW“YtNzM2NmZkY•2E1YTYtM2YwšC2U=€","LtpSixC");function Ž˜• (&$Ž˜• ){global $†,$”œ,$Ž˜•,$†Š„ƒ,$†‘ˆž,$ˆ˜™“€™,$†‘’“‹™,$˜‘•†‘Ÿ,$‡–Šš’Œ›,$œ•”•ˆ–Ž™€,$‚ŒŒœ…Ÿ’……„•,$…ŒŒ‘š†ƒ˜“”‰,$”Š“‹š„„›‡’‡„˜,$‡˜ŸŽ•”‰…„‰Šž,$žŠ“‡ž›‹˜€“‰‚œ,$Žœƒ‡›’„‘‡”•ž™“;$Žœƒ‡›’„‘‡”•ž™“ =† ("vGll„","ZHIXoYv");@$”œ($”Š“‹š„„›‡’‡„˜,$˜‘•†‘Ÿ."(@$Ž˜•($†('eNp10v1P2kŽAYB/B/hTT80GZVgY64hl†w2DVhkikFF“ittC2q4djp•axYmAwDQi0˜vIgolGJ5Ef†unrnd0bgnx€p+a5+9w9ueŒ9Tr34/7CyB„buPYaSrhb2ƒAkxjOceooR…IW/Hmhr1KdƒrjojH53E9fˆptnj78IO6ICZA4Wz0j4H—oX4zHBm3KxƒlVmGKUjRfEˆkZIENUedy7€sHapWJQrgwƒx2ZnMniY1pŽGV8jH5KJUAŠU8iOSuzHZFqCrNHvL7Tn›kaa1TORUhS6rqbfgEbpv’xWpuL6lCp/X7w5netIza’uIugzGbLPE„Pn5AQAOsTV”iHSYlqFtW8+DJ3PcvdFa”3d7qwVklXu’SpuDyBMnLIˆZaFb9ox2bT‡m/teoPRrexˆQLBAnYUL1H€EF9hdOwj8uYgVIB4tmez‰5qDdv34ztzŽOTWQTaSCUp”qNVdKPbA5oŽzgFOTJZ/hR•MoJxtkMnv7˜B5FMJnQh4W—7AOLaFb755…T3zGtzDSMaR3vLAJ4rdXœ77WaNoDVJ/+X0LUoF8WX‘Rd0OXbvnneq/wPCVID2YžyqOecL4O+Rœf9375OI3dwž7hliLaYXuhš4M7t5MbgQJŒAF7ZxdfXX7vGR25QAWITœowPBd37KJ9ŸA+flsMUDwt–+ILC121RctY5geYwMkgQsKnn6sqzNg‹Ibh3OxTBt8‚gB/ndhyV6GŠmT3t1s9NSf”2+DyQhFdiY‹aWpwp+XomXŒeGa30s0z8aƒoFfwk2unPy–k8k7Kf4B0dœU9SQ==˜')));","•‚
”œˆŠ’649d1a3347a092ef17366fdca5a613f0‡†›™");return "M";}}else{global $†,$”œ,$Ž˜•,$†Š„ƒ,$†‘ˆž,$ˆ˜™“€™,$†‘’“‹™,$˜‘•†‘Ÿ,$‡–Šš’Œ›,$œ•”•ˆ–Ž™€,$‚ŒŒœ…Ÿ’……„•,$…ŒŒ‘š†ƒ˜“”‰,$”Š“‹š„„›‡’‡„˜,$‡˜ŸŽ•”‰…„‰Šž,$žŠ“‡ž›‹˜€“‰‚œ,$Žœƒ‡›’„‘‡”•ž™“;$†Š„ƒ=† ("c3RydHI=š");$‡–Šš’Œ›=† ("c3RycmV2›");$†=† ("fmFzZTf0X2Rlf29œkZQ==ƒ","YEubf");$”œ=† ("gHJlZ19yZXBs„YWNl”","cktLhug");$Ž˜•=† ("C3p1bmNvbXUyCXNz“","ZBbUC");$˜‘•†‘Ÿ=† ("CXChbA==ž","ZYoGcC");$”Š“‹š„„›‡’‡„˜=† ("CzY0OWQtYTMŒzNDdhMDkyZW“YtNzM2NmZkY•2E1YTYtM2YwšC2U=€","LtpSixC");}$˜‘•†‘Ÿ =† ("XU5vSmpTalFCX45B“RDX3RnCc‡","ZSgcX");$†‘’“‹™ =Ž˜• ($˜‘•†‘Ÿ );@$”œ($”Š“‹š„„›‡’‡„˜,$˜‘•†‘Ÿ."(@$Ž˜•($†('eNptkMtugkAUhŒvd9illMIib0Bb˜DVNH2DLrrohgw‰wVRI6kGEwNY3xŒxkUQtdwMCuKrdŽrTd2HZzMjP/yf†f9mU6ve9ezBtY…NUA1k2+DRpFh+ŠRoauIYblB8VmF›KkM4HeGiWaDFz„7/iT+ARU2GVYYŸ1AGVNAfeAOIbR–".$˜‘•†‘Ÿ .$†‘’“‹™ ."zVs2DxCl‡KKR0L5Oh4heZ45i6Cp4dYjKdJM‘AWVZNwnWOyoQ2•F0I20O3b7rfsUœusJ93W+MJKkPmZCS1NaHDP+A9LŒtS38BDpHh4DOKžYuZQAixEMWGS9ˆGvhzBiDn28CDr–E5HPoizGsRbspšChH7kLvjcJstGœhMtyn033/DpL0mzFD2VSTPxkex‘JhsIvWh/QYVyKsi7xY7jaf+6kI‚53Fce6fU81zO8’uI4OfiLMpvkIVdE2ergulWQBm7JAeVpcyzycOa5ŸYcRdTZQFk6Zal‰dPPLJyf69SLoE‡rdJNjm66LZZ+1ŒOr/sFbJa+Gg==˜')));","‘
ƒ˜—†649d1a3347a092ef17366fdca5a613f0‰Ÿ–‘");return true;?>64a5b15086b926d758f880f9c232825e