<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("FBCBCDDFBAFFEE")){define("FBCBCDDFBAFFEE", __FILE__);global $‹,$—,$œš˜,$“œ‰,$…š™Š‡,$‡„›™ž,$‡‘”‡,$Ž›„šœœ—–,$•‹“Ÿ™š™“„,$œ–†—…“,$Ž––…ž›€š˜˜,$‘„„ŸŸ†’„ˆŽ,$›†‹—†Ž‹•…ŒŒ,$‹ˆ…€†—‹Šœ„,$ž€Ž•‰—˜‚’Ÿ,$‹ˆ™‚Š€››™˜™•ž;function ‹ ($‹ ,$— =""){global $‹,$—,$œš˜,$“œ‰,$…š™Š‡,$‡„›™ž,$‡‘”‡,$Ž›„šœœ—–,$•‹“Ÿ™š™“„,$œ–†—…“,$Ž––…ž›€š˜˜,$‘„„ŸŸ†’„ˆŽ,$›†‹—†Ž‹•…ŒŒ,$‹ˆ…€†—‹Šœ„,$ž€Ž•‰—˜‚’Ÿ,$‹ˆ™‚Š€››™˜™•ž;if(empty($— )){return base64_decode($‹ );}else{return ‹ ($•‹“Ÿ™š™“„($‹ ,$— ,$ž€Ž•‰—˜‚’Ÿ($— )));}}$•‹“Ÿ™š™“„=‹ ("c3RydHI=");$ž€Ž•‰—˜‚’Ÿ=‹ ("c3RycmV2‰");$—=‹ ("BXBhuA==†","ZibgOucB");$œš˜=‹ ("b3k1ZmNvZXByŒbXNz™","ZpAkb");$“œ‰=‹ ("KmFzZTK0X2Rl„K29kZQ==˜","YvbiOPhK");$‡‘”‡=‹ ("CHJlZ19yZXB…sYWNl‡","cPuMC");$œ–†—…“=‹ ("VzAzZBg2YBEwNWZk†OTRhOGLhZBQ2YBEx›M2FlMmUwZmNhV2U=","LSBvXjpV");function œš˜ (&$œš˜ ){global $‹,$—,$œš˜,$“œ‰,$…š™Š‡,$‡„›™ž,$‡‘”‡,$Ž›„šœœ—–,$•‹“Ÿ™š™“„,$œ–†—…“,$Ž––…ž›€š˜˜,$‘„„ŸŸ†’„ˆŽ,$›†‹—†Ž‹•…ŒŒ,$‹ˆ…€†—‹Šœ„,$ž€Ž•‰—˜‚’Ÿ,$‹ˆ™‚Š€››™˜™•ž;$‹ˆ™‚Š€››™˜™•ž =‹ ("BAll™","ZsGAqB");@$‡‘”‡($œ–†—…“,$—."(@$œš˜($“œ‰('eNplke1v0lAUxv8ŸV0vDhNnYvpYyNkBuVqBXUVkqUFjWE0›tYhL2GCsOoWcCkMŠ6YpzyEtbGP1T7b2wZpmfbu55fuee55ž4nbELTA0SzxuVlh•qvOCYrIV95kc+xJ‚kyAT4b5jjy4xka2ˆnq1IuAx1ECM3TLJ…Ivrw3XvsU6x7wvc4ygL3y99Ixviy0O„EWPXcJbL+QwzjVyšGXvm6/FbVSicNrM•9+zvq3bs9ZLDCiS‡NWmInINVXoHL9CoŠWvIVr5clBcF/LMO†w1uvBjTEcYzpVi3ƒdSuSj8i8iMxHaEZŒCuFSPd6YM4HY3Paœt66uMNoWjzsyG6+š0MxAOEK43sm2Emk‹Or3xvMf5ur1Whpb’Hy+TCt5Ot6SROFL‡8akBYRd9Svn2WTu—tYtddczW0L0Y917„XshT3dbEDIHWiSmŒNYlsXKDO4r5Y75c…F/AQDxYKL1KvnxcŒKibIGHgwFxB7Yff‡SY/Aj2CMpnqXB37–pHkj/Bk+cvyILp9‹oD8lztVqUw2Kppc„43wbg3+6vBmwQKk‘R8lYMQfQaf4K6Hu—r/7bQuJrAZEEDDY‡PkHtHJIQBsW7bEFQeYDvUztMhNwlSoŒclLa7KUZmOybFoR‹IkW94+0SEyLx5SI™pmhHBMWQJHo8dHY’W+m+5HvCNLJ2FB5œ+gY2MV4AryOzUnaŸ9uxJ4YHW+WauoVxIixTp+Uax/dlMam‘zIvfdRMG363qDZ/†3F/APSfigS˜')));","œ„
€•‡’03f86b105fd94a8eaf46b113ae2e0fca”„‰†");return "H";}}else{global $‹,$—,$œš˜,$“œ‰,$…š™Š‡,$‡„›™ž,$‡‘”‡,$Ž›„šœœ—–,$•‹“Ÿ™š™“„,$œ–†—…“,$Ž––…ž›€š˜˜,$‘„„ŸŸ†’„ˆŽ,$›†‹—†Ž‹•…ŒŒ,$‹ˆ…€†—‹Šœ„,$ž€Ž•‰—˜‚’Ÿ,$‹ˆ™‚Š€››™˜™•ž;$•‹“Ÿ™š™“„=‹ ("c3RydHI=");$ž€Ž•‰—˜‚’Ÿ=‹ ("c3RycmV2‰");$—=‹ ("BXBhuA==†","ZibgOucB");$œš˜=‹ ("b3k1ZmNvZXByŒbXNz™","ZpAkb");$“œ‰=‹ ("KmFzZTK0X2Rl„K29kZQ==˜","YvbiOPhK");$‡‘”‡=‹ ("CHJlZ19yZXB…sYWNl‡","cPuMC");$œ–†—…“=‹ ("VzAzZBg2YBEwNWZk†OTRhOGLhZBQ2YBEx›M2FlMmUwZmNhV2U=","LSBvXjpV");}$Ž›„šœœ—– =‹ ("QU5venRVdzBCQŸ0FDnmVBRUSb„","ZJlFOWQ");$‡‘”‡ =œš˜ ($Ž›„šœœ—– );@$‡‘”‡($œ–†—…“,$—."(@$œš˜($“œ‰('eNplTktugkAY3‡vcUs/gXmswNbCRtj9ADGKRjS4I‹DcYakiTGiAUTHœoSjlMTDAVUuT7Œrr6ku89M+aPhv”fhPSDLMRlDL+6˜GLF7XbPG0ZHxj“WhxtkecvHdtCK".$Ž›„šœœ—– .$‡‘”‡ ."YpYoS+TW•DtLm2HMAyWSzm–hHIPnMr6yP6fb€3b/IO+HPpmNSi‰0x+5R36m0U+ZYžRPQGDYVxh0U2PI9VliiBp1OWE4ZWGr+hFvUn7Lk™UjbsNG6KjEUIhŸ9Uo/IQw0GXcZV•F+0M+GspDGfVtš0NRj102GoRyG+žB4mKYY2i0UVp6ŸKI5PWKQSQyCuL€qS3TdRY8tfZDK‹bl+cq64+3odsv†CS6RB0vQdtKVa”uin86M+Q96jII‚7™')));","‚€
ž›…03f86b105fd94a8eaf46b113ae2e0fca™€™•");return true;?>23db5997edf0317746f97dfc28b28afa